package chick.extrabotany.common.loots;

import chick.extrabotany.ExtraBotany;
import net.minecraft.core.Registry;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.storage.loot.functions.LootItemFunctionType;
import net.minecraft.world.level.storage.loot.predicates.LootItemConditionType;
import vazkii.botania.common.loot.BindUuid;
import vazkii.botania.common.loot.EnableRelics;
import vazkii.botania.common.loot.RealPlayerCondition;
import vazkii.botania.common.loot.TrueGuardianKiller;


public class ModLootModifiers
{
    public static final LootItemConditionType TRUE_GUARDIAN_KILLER = new LootItemConditionType(new TrueGuardianKiller.Serializer());
    public static final LootItemConditionType ENABLE_RELICS = new LootItemConditionType(new EnableRelics.Serializer());
    public static final LootItemConditionType KILLED_BY_REAL_PLAYER = new LootItemConditionType(new RealPlayerCondition.Serializer());
    public static final LootItemFunctionType BIND_UUID = new LootItemFunctionType(new BindUuid.Serializer());
    public static void init() {
        Registry.register(Registry.LOOT_CONDITION_TYPE, new ResourceLocation(ExtraBotany.MODID,"true_guardian_killer"), TRUE_GUARDIAN_KILLER);
        Registry.register(Registry.LOOT_CONDITION_TYPE, new ResourceLocation(ExtraBotany.MODID,"enable_relics"), ENABLE_RELICS);
        Registry.register(Registry.LOOT_CONDITION_TYPE, new ResourceLocation(ExtraBotany.MODID,"killed_by_player"), KILLED_BY_REAL_PLAYER);
        Registry.register(Registry.LOOT_FUNCTION_TYPE, new ResourceLocation(ExtraBotany.MODID,"bind_uuid"), BIND_UUID);
    }
}
